language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    
cache:
  - composer

addons:
  hostname: wordpress.dev
  sauce_connect: 
    username: rvodden
  jwt:
    secure: "j4epCGJJhbZEHkL/dJsyycg+l/GHgDWFVyELkZOOVfH42+OhXnILAlY6xqp3cQNLg17LUlzIBA0Kc8PEtmZINJyhaEkSgo3TMfR5G75jizedu22yhzrfmZICyNxiK/bAQ2jbZ124odhuYyN6HtNfQiqlCL5Y1H2GP5v1ogfBss+wO1j2FkBSUduA3gU6VgvfcDyPEpByUnmaSa9ki0I8PrXPxl6gdFqT7rp/kAWWOn/1gsq7Fwzt4qncI+DCTxqOs3e0Q128ZeLnBerO3ZUMBZXM8TMYldXvX7o12PrVbji///KkpsVm83GrjNeA4wL8PWmhPxjIwuaOaI6a2RfiAUrnrqwTiniQdylfIZX5QuAm/jaBBzzX9TZAKLZ63n5VJk+ZXkmrvzz3JWdGJbxYJIQV5+YUip0aJSbBjurO0L4r5OV6GJI6ggtZ10yiJI3z6hL+6AbSFu1mVbD17gpHTPg1Q20vwyjQaoJT87p/urDNr44qZyJKYWk9ISthQf+HuXUnxH2ba6nyFeKfcLn3cjDH99Oz5cm5vxcpdR3KjCElf9C/CNoKA526atOK7C3tZTkKmpGgfBno/0yt8CgoqAjw+lRQQrhCoAxjSq1qLhdo4jlJ73j8KwD4HfjwYDOgIJZw3KQizvqJmzzRHzPtqG97VYvGXSgxyiZWflo/htg="

php:
  - 7.0.22
  
env:
  - WP_VERSION=latest WP_MULTISITE=0

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$(pwd)/vendor/bin:$PATH"
  - sudo apt-get update
  - mysql -u root -e 'CREATE DATABASE wordpress;'
  - mysql -u root -e "CREATE USER 'travis'@'127.0.0.1' IDENTIFIED BY '';"
  - mysql -u root -e "GRANT ALL ON wordpress.* TO 'travis'@'127.0.0.1';"
  
install:
  - composer install
  # install wordpress
  - wp core download  --path=/tmp/wordpress
  - wp core config --dbname=wordpress --dbuser=travis --dbhost=127.0.0.1 --dbpass= --path=/tmp/wordpress
  - wp core install --admin_name=admin --admin_password=admin --admin_email=admin@example.com --url=http://wordpress.dev --title=WordPress --path=/tmp/wordpress
  # link plugin in to the wordpress location
  - ln -s $(pwd) /tmp/wordpress/wp-content/plugins/concert-manager
  # activate the plugin
  - wp plugin activate concert-manager --path=/tmp/wordpress
  #
  # install apache and enable current version of php
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo /etc/init.d/apache2 restart

script:
  - phing citest
  - behat -p ci
  
after_script:
  - travis_retry php vendor/bin/coveralls --verbose --coverage_clover=reports/php/phpunit.coverage.xml
