dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    
php:
  - 7.0
  
env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$(pwd)/vendor/bin"
  - composer install

script:
  - echo $JAVA_HOME
  - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php' -not -path './vendor/*')
  - phpunit
  - travis_retry php vendor/bin/coveralls --verbose --coverage_clover=reports/php/phpunit.coverage.xml
